version: "3"
services:
  node:
    build: .
    networks:
      - backend
    volumes:
      - .:/usr/src/app/
      - /usr/src//app/node_modules
    ports:
      - "3000:3000"
  mongo:
      image: mongo
      restart: always
      networks: 
        - backend
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      volumes:
        - mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    networks: 
        - backend
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
networks:
  frontend:
  backend:
  
volumes:
  mongodata: